version: "3"

services:
  # drface-api:
  #   container_name: drface-api
  #   image: ruhyadi/drface:v0.1.0
  #   restart: always
  #   env_file:
  #     - .env
  #   volumes:
  #     - $PWD:/app
  #   ports:
  #     - ${API_PORT}:${API_PORT}
  #   expose:
  #     - ${API_PORT}
  #   command: python src/main.py mode=api
  #   depends_on:
  #     - drface-mongodb

  # drface-mongodb:
  #   container_name: drface-mongodb
  #   image: mongo:6.0.3
  #   restart: always
  #   env_file:
  #     - .env
  #   volumes:
  #     - $PWD/data/mongodb:/data/db
  #   ports:
  #     - ${MONGO_PORT}:${MONGO_PORT}
  #   expose:
  #     - ${MONGO_PORT}
  #   command: mongod --port ${MONGO_PORT}

  drface-engine-facenet:
    container_name: drface-engine-facenet
    image: openvino/model_server:2022.3
    user: 1000:1000
    env_file:
      - .env
    volumes:
      - $PWD/weights/facenet:/weights/facenet
    ports:
      - ${ENGINE_FACENET_GRPC_PORT}:${ENGINE_FACENET_GRPC_PORT}
      - ${ENGINE_FACENET_REST_PORT}:${ENGINE_FACENET_REST_PORT}
    expose:
      - ${ENGINE_FACENET_GRPC_PORT}
      - ${ENGINE_FACENET_REST_PORT}
    command: |
      --model_name facenet
      --model_path /weights/facenet
      --port ${ENGINE_FACENET_GRPC_PORT}
      --rest_port ${ENGINE_FACENET_REST_PORT}
      --target_device CPU