# Main hydra configurations

# Default configurations
defaults:
  - _self_
  - api: [main_api]
  - logger: [default] 
  - database: [mongodb_database]
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none

# Override hydra output directory
hydra:
  run:
    dir: .
  output_subdir: null

# override logger level
logger:
  level: DEBUG

# service mode
mode: api 